In [2]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv("results.csv")
data

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral,Result_team1
0,2/3/1900,Scotland,Wales,5,2,British Home Championship,Aberdeen,Scotland,False,Win
1,2/24/1900,Wales,Northern Ireland,2,0,British Home Championship,Llandudno,Wales,False,Win
2,3/3/1900,Northern Ireland,Scotland,0,3,British Home Championship,Belfast,Ireland,False,Lose
3,3/17/1900,Northern Ireland,England,0,2,British Home Championship,Dublin,Ireland,False,Lose
4,3/26/1900,Wales,England,1,1,British Home Championship,Cardiff,Wales,False,Draw
...,...,...,...,...,...,...,...,...,...,...
48759,12/12/2025,Jordan,Iraq,1,0,Arab Cup,Al Rayyan,Qatar,True,Win
48760,12/12/2025,Algeria,United Arab Emirates,1,1,Arab Cup,Al Khor,Qatar,True,Draw
48761,12/15/2025,Morocco,United Arab Emirates,3,0,Arab Cup,Al Rayyan,Qatar,True,Win
48762,12/15/2025,Saudi Arabia,Jordan,0,1,Arab Cup,Al Khor,Qatar,True,Lose
48763,12/18/2025,Jordan,Morocco,2,3,Arab Cup,Lusail,Qatar,True,Lose

In [19]:
x = data[["date","home_team","away_team","Result_team1"]]
x.tail()

             date     home_team             away_team Result_team1
48759  12/12/2025        Jordan                  Iraq          Win
48760  12/12/2025       Algeria  United Arab Emirates         Draw
48761  12/15/2025       Morocco  United Arab Emirates          Win
48762  12/15/2025  Saudi Arabia                Jordan         Lose
48763  12/18/2025        Jordan               Morocco         Lose

In [7]:
data1 = pd.read_csv("dataset2.csv")
data1

,Date,Match,Team1,Team2,Team1_rank,Team2_rank,Team1_Star_Player_Count,Team1_Top100_players,Team2_Star_Player_Count,Team2_Top100_players,Team1_Recent_form,Team2_Recent_form,Head_to_Head_Team1_result_precentage,Team1_Result,Team1_goalkeeper_rank,Team2_goalkeeper_rank
0,2002/06,2002FrancevsSenagal,France,Senegal,1,42,1,6,0,2,NaN,NaN,NaN,-1,3,19
1,2002/07,2002UruguayvsDenmark,Uruguay,Denmark,24,20,0,1,0,2,NaN,NaN,NaN,-1,14,9
2,2002/07,2002DenmarkvsSenegal,Denmark,Senegal,20,42,0,2,0,2,NaN,NaN,NaN,0,9,19
3,2002/07,2002FrancevsUruguay,France,Uruguay,1,24,1,6,0,1,NaN,NaN,NaN,0,3,14
4,2002/07,2002DenmarkvsFrance,Denmark,France,20,1,0,2,1,6,NaN,NaN,NaN,1,9,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378,2022/11,2022MorvsPor,Morocco,Portugal,22,9,1,3,3,6,NaN,NaN,NaN,1,16,7
379,2022/11,2022ArgvsCro,Argentina,Croatia,3,12,3,6,2,4,NaN,NaN,NaN,1,5,10
380,2022/11,2022FravsMor,France,Morocco,4,22,4,8,1,3,NaN,NaN,NaN,1,4,16
381,2022/11,2022_Final_ArgvsFra,Argentina,France,3,4,3,6,4,8,NaN,NaN,NaN,0,5,4
382,2022/11,2022CrovsMor,Croatia,Morocco,12,22,2,4,1,3,NaN,NaN,NaN,1,10,16

In [ ]:
def get_recent(row):
    input_date = pd.to_datetime(row["Date"])
    fi_team1 = row["Team1"]
    fi_team2 = row["Team2"]


    date_fill = x[pd.to_datetime(data1["date"]) < input_date ]
    clear_data = date_fill[fi_team1].tail()
    
    


clran = data1.apply(get_recent, axis=1)

KeyError: 'France'